### ISSUE TITLE
Add strict checks on model/provider/service/resource names

### ISSUE THREAD

**Issue by tcalmant** [eclipse/org.eclipse.sensinact.gateway#124]
Names used to identify SensiNact concepts (model, provider, service, resource and possibly metadata) must be valid topic segment else we get errors during the notification process.

A possible solution would be to reject concepts containing unsupported characters in their name before registering them in the Nexus.

Here is an example of error we currently get for a resource name containing a dot:
```java
Illegal character 46 at index 52 of topic string: LIFECYCLE/XXXXXXXXXX-airquality-NNNNNNN/pollutant/PM2.5
        at org.apache.aries.typedevent.bus.impl.TypedEventBusImpl.checkTopicSyntax(TypedEventBusImpl.java:495)
        at org.apache.aries.typedevent.bus.impl.TypedEventBusImpl.deliver(TypedEventBusImpl.java:410)
        at org.eclipse.sensinact.prototype.notification.impl.NotificationAccumulatorImpl.lambda$doComplete$5(NotificationAccumulatorImpl.java:316)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
        at java.base/java.util.AbstractList$RandomAccessSpliterator.forEachRemaining(AbstractList.java:720)
        at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762)
        at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:276)
        at java.base/java.util.TreeMap$ValueSpliterator.forEachRemaining(TreeMap.java:3215)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
        at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
        at org.eclipse.sensinact.prototype.notification.impl.NotificationAccumulatorImpl.doComplete(NotificationAccumulatorImpl.java:316)
        at org.eclipse.sensinact.prototype.notification.impl.AbstractNotificationAccumulatorImpl.completeAndSend(AbstractNotificationAccumulatorImpl.java:98)
```

**Comment by timothyjward** [comment]
@juergen-albert is this handled by #320 ?

**Comment by timothyjward** [comment]
@tcalmant @juergen-albert - I think this may be done now. Can you confirm?

**Comment by juergen-albert** [comment]
We should create an integration test for this. @tcalmant can you do this, as I'm will not find the time in the near future?

**Comment by tcalmant** [comment]
I won't be able to do an IT before May.
I'm not sure the issue is fixed: IIRC @juergen-albert , the names of providers, services and resources are normalized before being stored in the model, but are always seen in their given form in the event URI, am I right?
